### ISSUE TITLE
Default translation support

### ISSUE THREAD

**Issue by al0mie** [vsch/laravel-translation-manager#62] opened 2017-02-10 18:17 UTC
Hello. Thanks for great work. It's only one question. How about support default translations? It seems in regex you always seach values with key: ([.][^\1)]+)+" , but translations can be in resources/lang/en.json example and call __('someValue'). So now there no way to sync their? Some thoughts about it?

**Comment by vsch** [comment] 2017-02-11 13:15
@al0mie, currently there is no support for json translation files. 

Default translations were not available when this package was developed. 

What is the advantage of using default translations?

**Comment by al0mie** [comment] 2017-02-11 15:38
@vsch, I guess for using translation as is if it not exists, so __('I love coffee') return I love coffee if not exist value in file. Using simple lang function return something like message.I love coffee. 

Also it possible to store common messages (not to define specific files like message.php).

Seems, it was proposed here https://github.com/laravel/internals/issues/252

So maybe add some kind of handler for sync this?

**Comment by vsch** [comment] 2017-02-11 15:55
@al0mie, I looked at the justification and in my opinion it solves nothing but a lazy approach to translations. Having duplicate short keys is a problem caused by lack of standard and coordination in the development team which is not addressed by the default translations. Nothing stops developers from creating similar but different strings for the same items. 

Also lumping all translations into a single file does not seem like a good way to break up large site translations.

With LTM the typical use case I use, is to create the UI with keys without creating any files or translations. Then go into LTM web UI and use "Auto Fill" to quickly convert keys to text. Later these auto filled translations can be adjusted for correct formulation and translations to other languages can be applied.

The other issue is translation keys can have limits on characters they contain while strings used for default translations do not. This causes a lot of issues for LTM since it passes "keys" in the URL and Laravel does not handle some combinations even when URL encoded. Right now translation keys containing some combinations of characters will cause LTM not work for these. This limitation was inherited from the original package.

Being able to handle any characters in translation keys is a big rework of the package and would be pre-requisite to handling default translations. If someone wants to do this work I would welcome it.

**Comment by al0mie** [comment] 2017-02-12 20:23
@vsch, thanks for extended answer, I guess you are right. 

> Being able to handle any characters in translation keys. 

Maybe it's not possible for limitation of format files, but it is not common cases.

> This causes a lot of issues for LTM since it passes "keys" in the URL and Laravel does not handle some combinations even when URL encoded.

Any ideas how better do it?

**Comment by vsch** [comment] 2017-02-12 20:27
@al0mie, ideally the WebUI support should be changed to use post instead of get with parameters on the URL.

Also, JS code assumes it can use the translation key for valid identifiers HTML. This is also another roadblock to making arbitrary keys. It would require changing how lookup is done for translations in JS code.

**Comment by al0mie** [comment] 2017-02-12 20:59
@vsch, yes, I understand you. I'll think about it. Maybe do some refactoring before it, seems it's more important.

**Comment by vsch** [comment] 2017-02-13 01:50
@al0mie, I did the most work on this package when I desperately needed the functionality for a project and had no time budget for it. A lot of functionality was hacked into existing implementation with quite a bit of clean-up afterwards but never had the time to rework it to allow arbitrary keys.

If you do look into it and have questions, don't hesitate to ask.

**Comment by gerardreches** [comment] 2017-05-23 15:03
I asked [this same question in the original repository](https://github.com/barryvdh/laravel-translation-manager/issues/190), but since Barry doesn't have time for the project, it was not worth going deeper into the question.

I would like to see this implemented, so I would be glad to help in what I can, but the one who knows better how the package works is you @vsch.

Could you indicate a strategy to follow to implement this functionality?

**Comment by vsch** [comment] 2017-05-23 15:27
@gerardreches, this functionality can touch on every aspect of the translation package: import, DB, export, cache, WebUI and `Translator` service or at least import, export, cache, WebUI and translator.

The simplest way to do this would be to:

1. Parse the JSON translation files and store them in the `JSON::` group with a fake short key for all translations in the DB so that DB and WebUI for these is not distinguishable from standard translations.  However, I would add a fake locale, say `_` that is not editable that represents the original key string. This way you could create a translation for the primary locale for the string, changing the translation string used. Otherwise you will not be able to have a JSON translation file for the primary locale.

2. In export determine when the group is a JSON destination file and export these files in JSON format using the fake locale string as the translation key.

3. Cache should also be updated in those cases where it is enabled to override file content with cached values. Since the key is the fake locale string then `JSON::` group should use this as the key not the short key. The rest should be automatic.

4. Translator should know how to handle JSON group translations that are cached.

5. Showing which values are cached in the WebUI (uses alternate background for these translations) should also be looked at in the case of `JSON::` group to make sure it works as expected.

   Also the fake `_` locale should be excluded from all the locale editing since changing that will make all the key strings out of sync with the code.

First iteration might uncover a few kludges but should be workable.

**Comment by vsch** [comment] 2018-10-23 22:38
This has been implemented in the master branch for Laravel 5.6

**Closed as completed by vsch** 2018-10-23 22:38 UTC
