### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by pilis** [vsch/laravel-translation-manager#120] opened 2018-05-28 10:58 UTC
When I call  `php artisan translations:export <whatever>` I get `In TranslationFileRewriter.php line 111: count(): Parameter must be an array or an object that implements Countable`.

I'm using Laravel 5.5 with `"vsch/laravel-translation-manager": "~2.5"`.

I tried to investigate why it's that and I come down with the $chars param eqals string with new line only. I have been using this package so far, but after update this happened.

**Comment by vsch** [comment] 2018-05-28 12:15
@piotr-pilis, I will take a look at the code for ~2.5. The issue was fixed in ~2.6 branch.

The changes are caused by PHP 7 changes which only return count() for an array or object so the condition needs to test first if the param is an array before using count(). Previous versions of PHP had no issue with this.

**Comment by vsch** [comment] 2018-06-08 17:22
@piotr-pilis, fixed by #122, new version released 2.5.8

**Closed as completed** 2018-09-17 14:23 UTC
Labels: ☹ bug, fixed :)
